apiVersion: v1
kind: Service
metadata:
  name: cc-service
  labels:
    app: ccd-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: cc-webhttp
      targetPort: 8080
      protocol: TCP
  selector:
    name: cc-web
