# Spring Properties
spring:
  application:
     name: backend-webapp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port