# Spring Properties
spring:
  application:
     name: backend-webapp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
      
hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 15000
              
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port
  session:
    cookie:
      name: NLISESSIONID
      http-only: true